import Head from "next/head";
import Styles from "@/styles/Home.module.css";

//!Etapas;
import YourName from "@/components/YourName";
import YourCpf from "@/components/YourCpf";
import YourWhatsApp from "@/components/YourWhatsApp";
import YourBirthday from "@/components/YourBirthday";
import YourEmail from "@/components/YourEmail";
import Warning from "@/components/Warning";



export default function Home() {

  const formComponents = [
    <YourName />,
    <YourCpf />,
    <YourWhatsApp />,
    <YourBirthday />,
    <YourEmail />,
    <Warning />
  ];//!Array dos components;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={Styles.divMain}>
          <div className={Styles.divColor}>
            <div className={Styles.divCircleL}></div>
            <div className={Styles.divCircleR}></div>
            {/* Mensagens */}
            <div className={Styles.divFormMain}>
              <p>Etapas</p>
              <form>
                <div className={Styles.inputContainer}></div>
                <div className="actions">
                  <button type="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8" />
                    </svg>
                    <span>Voltar</span>
                  </button>
                  <button type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" iewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8" />
                    </svg>
                    <span>Próximo</span>
                  </button>
                </div>
              </form>
            </div>
          </div>
          <div className={Styles.divArrow}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="currentColor"
              viewBox="0 0 16 16"
              color="#FFF"
            >
              <path
                fill-rule="evenodd"
                d="M8 1a.5.5 0 0 1 .5.5v11.793l3.146-3.147a.5.5 0 0 1 .708.708l-4 4a.5.5 0 0 1-.708 0l-4-4a.5.5 0 0 1 .708-.708L7.5 13.293V1.5A.5.5 0 0 1 8 1"
              />
            </svg>
          </div>
          <div className={Styles.divBottom}>
            {/* Confirm e Voltar */}
          </div>
          <div className={Styles.divProgres}>
            <div className={Styles.divProgresStars}></div>
          </div>
        </div>
      </main>
    </>
  );
}
